server:
  port: 8082

spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivty

  cloud:
    config:
      import-check:
        enabled: false
    # To use Spring Cloud Config, uncomment the line below:
    # import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
  spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest