spring:
  
  data:
    mongodb:
      uri: ${MONGO_URI_AI:mongodb://localhost:27017/fitnessrecommendation}

  rabbitmq: 
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  config:
    import-check:
      enabled: false
    # import: optional:configserver:http://localhost:8888 

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  

rabbitmq:  
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
gemini:
  api:
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?}
    key: ${GEMINI_API_KEY}
