server:
  port: 8081

spring:
  main:
    allow-circular-references: true

  

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: taytaypped@1707
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
